"""empty message

Revision ID: 03ba63986a38
Revises: d7d565f21d16
Create Date: 2021-04-20 23:32:02.572543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ba63986a38'
down_revision = 'd7d565f21d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('country', sa.String(), nullable=True))
    op.add_column('tournaments', sa.Column('max_rank', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('min_rank', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tournaments_country'), 'tournaments', ['country'], unique=False)
    op.create_index(op.f('ix_tournaments_max_rank'), 'tournaments', ['max_rank'], unique=False)
    op.create_index(op.f('ix_tournaments_min_rank'), 'tournaments', ['min_rank'], unique=False)
    op.add_column('users', sa.Column('osu_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'osu_rank')
    op.drop_index(op.f('ix_tournaments_min_rank'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_max_rank'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_country'), table_name='tournaments')
    op.drop_column('tournaments', 'min_rank')
    op.drop_column('tournaments', 'max_rank')
    op.drop_column('tournaments', 'country')
    # ### end Alembic commands ###
