"""empty message

Revision ID: 954a6affc538
Revises: d0854123eee6
Create Date: 2021-04-20 23:50:21.391963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954a6affc538'
down_revision = 'd0854123eee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('osu_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('osu_refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('osu_token_expiry', sa.DateTime(), nullable=True))
    op.drop_column('users', 'access_token')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('access_token', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'osu_token_expiry')
    op.drop_column('users', 'osu_refresh_token')
    op.drop_column('users', 'osu_access_token')
    # ### end Alembic commands ###
